Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Metrics/LineLength:
  Exclude:
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/puma.rb'
    - 'config/initializers/*'

inherit_from: .rubocop_todo.yml
